CREATE TABLE ASSIST ( 
  EmployeeID INT UNIQUE,
  CustomerID INT UNIQUE,
  PRIMARY KEY (EmployeeID, CustomerID),
  FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID),
  FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
  ); 
