CREATE TABLE ASSIST (
	EmployeeID INT,
	CustomerID INT,
	PRIMARY KEY (EmployeeID, CustomerID),
	FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID),
	FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
);
