CREATE TABLE CONTAIN (
	BookID INT,
	OrderID INT,
	Quantity INT,
	Cost FLOAT(4),
	PRIMARY KEY (BookID, OrderID),
	FOREIGN KEY (BookID) REFERENCES BOOK(BookID),
	FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID)
);
