CREATE TABLE CONTAINS ( 
  BookID INT UNIQUE, 
  OrderID INT UNIQUE,
  Quantity INT,
  Cost FLOAT(4),
  PRIMARY KEY (BookID, OrderID),
  FOREIGN KEY (BookID) REFERENCES BOOK(BookID),
  FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID)
  ); 
