CREATE TABLE WROTE ( 
  BookID INT UNIQUE, 
  AuthorID INT UNIQUE,
  PRIMARY KEY(BookID,AuthorID),
  FOREIGN KEY(BookID) REFERENCES Book(BookID),
  FOREIGN KEY(AuthorID) REFERENCES Author(AuthorID)
  ); 
