CREATE TABLE WROTE ( 
  BookID INT UNIQUE, 
  AuthorID INT UNIQUE,
  PRIMARY KEY(BookID,AuthorID),
  FOREIGN KEY(BookID) REFERENCES BOOK(BookID),
  FOREIGN KEY(AuthorID) REFERENCES AUTHOR(AuthorID)
  ); 
